- name: Auto-heal demo disk
  hosts: localhost
  become: yes
  gather_facts: no
  connection: local

  tasks:

    - name: Show disk usage BEFORE
      command: df -h /mnt/var_test
      register: before

    - debug:
        var: before.stdout_lines

    - name: Clean demo files
      shell: |
        rm -rf /mnt/var_test/*
      ignore_errors: yes

    - name: Show disk usage AFTER
      command: df -h /mnt/var_test
      register: after

    - debug:
        var: after.stdout_lines
